package com.dao;

import java.util.List;




import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.model.Product;
@Repository

public class ProductDaoImpl implements ProductDao
{
	@Autowired
	private SessionFactory sessionFactory;
	public  ProductDaoImpl(){
		System.out.println("ProductDaoImpl 	object is created");
	}



@Transactional
public void saveProduct(Product product) {
	
	Session session=sessionFactory.getCurrentSession();
	
	//insert into product values (autogeneratedvalue,"Titian Raga",3000,20,"Titan Raga Mother of Pearl Dial Analog Watch for Women")
	
	session.save(product);
	 }
@Transactional
    public List<Product> getAllProducts(){
    	Session session=sessionFactory.getCurrentSession();
    	Query query=session.createQuery("from Product");
    	List<Product>products=query.list();
    	return products;
    	
    	
    }
@Transactional
      public Product getProductById (int id) {
	Session session=sessionFactory.getCurrentSession();
	Product product =(Product)session.get(Product.class, id);
	return product;
}
@Transactional
      public void deleteProduct(int id){
    	  Session session =sessionFactory.getCurrentSession();
         Product p = (Product) session.get(Product.class, new Integer(id));

    	  session.delete(p);
      }



	
	
		
	}
    
      
     
  


